apiVersion: v1
kind: Service
metadata:
  namespace: crawler-bot
  labels:
    app: mongo
  name: mongodb-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  clusterIP: None