apiVersion: v1
kind: Service
metadata:
  name: bugsearchcrawler-service
  namespace: crawler-bot
spec:
  type: LoadBalancer
  selector:
    app: bugsearchcrawler-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80