apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugsearchcrawler-service
  labels:
    app: bugsearchcrawler-service
  namespace: crawler-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugsearchcrawler-service
  template:
    metadata:
      labels:
        app: bugsearchcrawler-service
    spec:
      containers:
        - name: bugsearchcrawler-service
          image: acrworkflow1684607545542.azurecr.io/bugsearchcrawler:latest
          ports:
            - containerPort: 80
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password
            - name: DB_CONN_STRING
              valueFrom: 
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
