apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  namespace: crawler-bot
  name: production-rabbitmqcluster
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 1700
                  default_user= 
                    valueFrom:
                      secretKeyRef:
                        name: rabbitmq-creds
                        key: username
                  default_pass = 
                    valueFrom:
                      secretKeyRef:
                        name: rabbitmq-creds
                        key: password
                  default_user_tags.administrator = true
  service:
    type: LoadBalancer