apiVersion: v1
kind: Service
metadata:
  namespace: crawler-bot
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30000